#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

sudo yabai --load-sa

# global settings
yabai -m config \
	mouse_follows_focus on \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_topmost on \
	window_shadow float \
	window_animation_duration 0.3 \
	window_opacity_duration 0.2 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.90 \
	window_opacity on \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 10 \
	bottom_padding 10 \
	left_padding 10 \
	right_padding 10 \
	window_gap 06 \
	layout bsp mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action stack

yabai -m config external_bar main:30:0
yabai -m config insert_feedback_color 0xffd65d0e

yabai -m rule --add app="^Neovide$" manage=on
yabai -m rule --add app="^neovide$" manage=on

# custom settings
# source https://github.com/anujc4/dotfiles/blob/master/macos_wm/yabai/yabairc
app_titles="(Copy|Bin|About This Mac|Info|Finder Preferences|Preferences|PicGo"
app_titles+="|QuickTime Player|Stickies)"
yabai -m rule --add title="${app_titles}" manage=off

app_names="^(Calculator|Authy Desktop|Postgres|VLC|System Preferences|IINA|GifCapture|Pomotroid"
app_names+="|iMazing HEIC Converter|AppCleaner|Stickies|1Password 7|VeraCrypt"
app_names+="|Tunnelblick|WireGuard|Logi Options|JetBrains Toolbox"
app_names+="|Inkscape Settings|Alfred|System Settings|System Preferences|System Information|Activity Monitor"
app_names+="|Logi Options\+|JetBrains Gateway|SteelSeries GG Client)$"
yabai -m rule --add app="${app_names}" manage=off

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai -m signal --add label=space_changed event=space_changed \
	action="$HOME/.config/yabai/save_recent_space.sh"

echo "yabai configuration loaded.."
