#!/bin/sh
# shellcheck disable=SC2094,SC2210,SC3028,SC2211,SC2171,SC2288
# Shellchecks disabled for this file
# SC2094: Make sure not to read and write the same file in the same pipeline.
# SC2210: This is a file redirection. Was it supposed to be a comparison or fd operation?
# SC3028: In POSIX sh, VARIABLE is undefined.
# SC2211: This is a glob used as a command name. Was it supposed to be in ${..}, array, or is it missing quoting?
# SC2171: Found trailing ] outside test. Add missing [ or quote if intentional.
# SC2288: This is interpreted as a command name ending with apostrophe. Double check syntax.

## ################################################################ #
# THE FOLLOWING IS AN EXPLANATION OF THE GRAMMAR THAT SKHD PARSES. #
# FOR SIMPLE EXAMPLE MAPPINGS LOOK FURTHER DOWN THIS FILE..        #
# ################################################################ #
# A list of all built-in modifier and literal keywords can
# be found at https://github.com/koekeishiya/skhd/issues/1
#
# A hotkey is written according to the following rules:
#
#   hotkey       = <mode> '<' <action> | <action>
#
#   mode         = 'name of mode' | <mode> ',' <mode>
#
#   action       = <keysym> '[' <proc_map_lst> ']' | <keysym> '->' '[' <proc_map_lst> ']'
#                  <keysym> ':' <command>          | <keysym> '->' ':' <command>
#                  <keysym> ';' <mode>             | <keysym> '->' ';' <mode>
#
#   keysym       = <mod> '-' <key> | <key>
#
#   mod          = 'modifier keyword' | <mod> '+' <mod>
#
#   key          = <literal> | <keycode>
#
#   literal      = 'single letter or built-in keyword'
#
#   keycode      = 'apple keyboard kVK_<Key> values (0x3C)'
#
#   proc_map_lst = * <proc_map>
#
#   proc_map     = <string> ':' <command> | <string>     '~' |
#                  '*'      ':' <command> | '*'          '~'
#
#   string       = '"' 'sequence of characters' '"'
#
#   command      = command is executed through '$SHELL -c' and
#                  follows valid shell syntax. if the $SHELL environment
#                  variable is not set, it will default to '/bin/bash'.
#                  when bash is used, the ';' delimeter can be specified
#                  to chain commands.
#
#                  to allow a command to extend into multiple lines,
#                  prepend '\' at the end of the previous line.
#
#                  an EOL character signifies the end of the bind.
#
#   ->           = keypress is not consumed by skhd
#
#   *            = matches every application not specified in <proc_map_lst>
#
#   ~            = application is unbound and keypress is forwarded per usual, when specified in a <proc_map>
#
# A mode is declared according to the following rules:
#
#   mode_decl = '::' <name> '@' ':' <command> | '::' <name> ':' <command> |
#               '::' <name> '@'               | '::' <name>
#
#   name      = desired name for this mode,
#
#   @         = capture keypresses regardless of being bound to an action
#
#   command   = command is executed through '$SHELL -c' and
#               follows valid shell syntax. if the $SHELL environment
#               variable is not set, it will default to '/bin/bash'.
#               when bash is used, the ';' delimeter can be specified
#               to chain commands.
#
#               to allow a command to extend into multiple lines,
#               prepend '\' at the end of the previous line.
#
#               an EOL character signifies the end of the bind.

# ############################################################### #
# THE FOLLOWING SECTION CONTAIN SIMPLE MAPPINGS DEMONSTRATING HOW #
# TO INTERACT WITH THE YABAI WM. THESE ARE SUPPOSED TO BE USED AS #
# A REFERENCE ONLY, WHEN MAKING YOUR OWN CONFIGURATION..          #
# ############################################################### #

# focus window
# alt - h : yabai -m window --focus west

# swap managed window
# shift + alt - h : yabai -m window --swap north
#shift + alt - h : yabai -m window --swap west || yabai -m window --swap east;\
#                  sketchybar --trigger window_focus

# move managed window
# shift + cmd - h : yabai -m window --warp east

# balance size of windows
# shift + alt - 0 : yabai -m space --balance

# make floating window fill screen
# shift + alt - up : yabai -m window --grid 1:1:0:0:1:1

# make floating window fill left-half of screen
# shift + alt - left : yabai -m window --grid 1:2:0:0:1:1

# create desktop, move window and follow focus - uses jq for parsing json (brew install jq)
# shift + alt - n : yabai -m space --create && \
#                   index="$(yabai -m query --spaces --display | jq 'map(select(."is-native-fullscreen" == false))[-1].index')" && \
#                   yabai -m window --space "${index}" && \
#                   yabai -m space --focus "${index}"

# fast focus desktop
# cmd + alt - x : yabai -m space --focus recent
# cmd + alt - 1 : yabai -m space --focus 1

# send window to desktop and follow focus
# shift + cmd - z : yabai -m window --space next; yabai -m space --focus next
# shift + cmd - 2 : yabai -m window --space  2; yabai -m space --focus 2

# focus monitor
# ctrl + alt - z  : yabai -m display --focus prev
# ctrl + alt - 3  : yabai -m display --focus 3

# send window to monitor and follow focus
# ctrl + cmd - c  : yabai -m window --display next; yabai -m display --focus next
# ctrl + cmd - 1  : yabai -m window --display 1; yabai -m display --focus 1

# move floating window
# shift + ctrl - a : yabai -m window --move rel:-20:0
# shift + ctrl - s : yabai -m window --move rel:0:20

# increase window size
# shift + alt - a : yabai -m window --resize left:-20:0
# shift + alt - w : yabai -m window --resize top:0:-20

# decrease window size
# shift + cmd - s : yabai -m window --resize bottom:0:-20
# shift + cmd - w : yabai -m window --resize top:0:20

# set insertion point in focused container
# ctrl + alt - h : yabai -m window --insert west

# toggle window zoom
# alt - d : yabai -m window --toggle zoom-parent
# alt - f : yabai -m window --toggle zoom-fullscreen

# toggle window split type
# alt - e : yabai -m window --toggle split

# float / unfloat window and center on screen
# alt - t : yabai -m window --toggle float --grid 4:4:1:1:2:2

# toggle sticky(+float), topmost, picture-in-picture
# alt - p : yabai -m window --toggle sticky --toggle topmost --toggle pip
#
#


############################# Configuration Start##################################
# fish shell do not use ${} to get the value of a variable
ctrl + alt + cmd - r : launchctl kickstart -k "gui/$UID/homebrew.mxcl.yabai"; \
                       launchctl kickstart -k "gui/$UID/homebrew.mxcl.sketchybar"
ctrl + alt + cmd - s : launchctl kickstart -k "gui/$UID/homebrew.mxcl.sketchybar"

# 0x24 is enter
ctrl + shift - 0x24  : open -na /Applications/Alacritty.app
ctrl + shift - k     : open -na /Applications/Forklift.app
ctrl + shift - q     : yabai -m window --close

############################# Mode definitions ##################################
:: default           : ~/.config/skhd/mode_controller.sh default # default mode: normal
:: stack   @         : ~/.config/skhd/mode_controller.sh stack # stack mode: interact with stacks
:: display @         : ~/.config/skhd/mode_controller.sh display # display mode: focus displays, move windows to other displays
:: window  @         : ~/.config/skhd/mode_controller.sh window # window mode: manipulate windows and spaces
:: resize  @         : ~/.config/skhd/mode_controller.sh resize # resize mode: resize windows in current space
:: inst    @         : ~/.config/skhd/mode_controller.sh inst # insert mode: tell yabai where to insert the new window

# Hack to use "ctrl + shift - r" keybinding in RubyMine
# to run tests but trigger resize mode everywhere else
default < ctrl + shift - r [
  "rubymine"   ~
  * : skhd -k "meh - r"
]

resize < ctrl + shift - r [
  "rubymine"   ~
  * : skhd -k "meh - r"
]

# Activate modes using the keybinding
default < ctrl + shift - d ; display
default < ctrl + shift - s ; stack
default < ctrl + shift - w ; window
default < meh - r          ; resize
default < ctrl + shift - i ; inst

# De-activate modes
display, window, resize, stack, inst < escape ; default

display < ctrl + shift - d ; default
stack   < ctrl + shift - s ; default
window  < ctrl + shift - w ; default
resize  < meh - r          ; default
inst    < ctrl + shift - i ; default

############################# Global modifiers ##################################
# The aim is to not have too many global key-bindings because it will clash with
# other application based keybindings e.g. VS Code, IntelliJ, etc.

# toggle fullscreen inside screen
# ctrl + shift - space  : yabai -m window --toggle zoom-fullscreen; \
#                         sketchybar --trigger window_focus
# escape with Alacritty vim mode
ctrl + alt - space  : yabai -m window --toggle zoom-fullscreen; \
#                         sketchybar --trigger window_focus



ctrl + shift - right  : yabai -m window --focus east || \
                        yabai -m window --focus west; \
                        sketchybar --trigger window_focus
ctrl + shift - left   : yabai -m window --focus west || \
                        yabai -m window --focus east; \
                        sketchybar --trigger window_focus
ctrl + shift - up     : yabai -m window --focus north || \
                        yabai -m window --focus stack.prev || \
                        yabai -m window --focus stack.last; \
                        sketchybar --trigger window_focus

ctrl + shift - down   : yabai -m window --focus south || \
                        yabai -m window --focus stack.next || \
                        yabai -m window --focus stack.first; \
                        sketchybar --trigger window_focus

ctrl - down           : yabai -m window --focus mouse; \
                        sketchybar --trigger window_focus

# vi like key bindings
ctrl + shift - l      : skhd -k "ctrl + shift - right"
ctrl + shift - h      : skhd -k "ctrl + shift - left"
ctrl + shift - k      : skhd -k "ctrl + shift - up"
ctrl + shift - j      : skhd -k "ctrl + shift - down"

# toggle window native fullscreen
ctrl + shift - f      : yabai -m window --toggle native-fullscreen

# Useful if window focus is lost
ctrl + shift - m      : yabai -m window --focus mouse

# Fast focus display (monitor)
ctrl + alt - left      : yabai -m display --focus west || yabai -m display --focus recent
ctrl + alt - right     : yabai -m display --focus east || yabai -m display --focus recent
ctrl + alt - up        : yabai -m display --focus north || yabai -m display --focus recent
ctrl + alt - down      : yabai -m display --focus south || yabai -m display --focus recent

# fast focus desktop
ctrl - left            : yabai -m space --focus prev
ctrl - right           : yabai -m space --focus next
ctrl - z               : yabai -m space --focus recent
ctrl - 1               : yabai -m space --focus 1
ctrl - 2               : yabai -m space --focus 2
ctrl - 3               : yabai -m space --focus 3
ctrl - 4               : yabai -m space --focus 4
ctrl - 5               : yabai -m space --focus 5
ctrl - 6               : yabai -m space --focus 6
ctrl - 7               : yabai -m space --focus 7
ctrl - 8               : yabai -m space --focus 8
ctrl - 9               : yabai -m space --focus 9
ctrl - 0               : yabai -m space --focus 10
ctrl + alt - 1         : yabai -m space --focus 11
ctrl + alt - 2         : yabai -m space --focus 12
ctrl + alt - 3         : yabai -m space --focus 13
ctrl + alt - 4         : yabai -m space --focus 14
ctrl + alt - 5         : yabai -m space --focus 15
ctrl + alt - 6         : yabai -m space --focus 16
ctrl + alt - 7         : yabai -m space --focus 17
ctrl + alt - 8         : yabai -m space --focus 18
ctrl + alt - 9         : yabai -m space --focus 19
ctrl + alt - 0         : yabai -m space --focus 20

ctrl + alt - z         : yabai -m window --focus recent

# Switch to space with window running in native full-screen mode. Only works with SIP disabled.
# TODO: Has to be fixed
# - key
ctrl - 0x1B            : yabai -m space --focus (yabai -m query --spaces --display |  jq 'map(select(."native-fullscreen" == 1))[0].index') 

# = key
ctrl - 0x18            : yabai -m space --focus (yabai -m query --spaces --display | \
                         jq 'map(select(."native-fullscreen" == 1))[1].index')

# float / unfloat window and center on screen
alt - f                : yabai -m window --toggle float; \
                         yabai -m window --grid 4:4:1:1:2:2; \
                         sketchybar --trigger window_focus

######################## Insert mode ###########################################

inst < left            : yabai -m window --insert west; skhd -k 'escape'
inst < down            : yabai -m window --insert south; skhd -k 'escape'
inst < up              : yabai -m window --insert north; skhd -k 'escape'
inst < right           : yabai -m window --insert east; skhd -k 'escape'
inst < s               : yabai -m window --insert stack; skhd -k 'escape'

######################## Stack mode ############################################

# Add the active window  to the window or stack to the {direction}
# Note that this only works when the active window does *not* already belong to a stack
stack < left           : yabai -m window west  \
                         --stack "$(yabai -m query --windows --window | jq -r '.id')"; \
                         skhd -k 'escape'

stack < down           : yabai -m window south \
                         --stack "$(yabai -m query --windows --window | jq -r '.id')" ; \
                         skhd -k 'escape'

stack < up             : yabai -m window north \
                         --stack "$(yabai -m query --windows --window | jq -r '.id')" ; \
                         skhd -k 'escape'

stack < right          : yabai -m window east  \
                         --stack "$(yabai -m query --windows --window | jq -r '.id')"; \
                         skhd -k 'escape'

# Toggle current space layout between stack and bsp
stack < space          : yabai -m query --spaces --space | \
                         jq -re ".type" | \
                         xargs -I {} bash -c \
                         "if [ {} = 'stack' ]; \
                         then yabai -m space --layout bsp; \
                         else yabai -m space --layout stack; \
                         fi"; \
                         skhd -k 'escape'

# Remove the current window from the stack. Only works if the space layout is bsp
#bash shell
#stack < b              : set -l window (yabai -m query --windows --window | jq -r '.id'); \
#                         yabai -m window east --stack $window || (yabai -m window $window --toggle float && yabai -m window $window --toggle float); \
#                         skhd -k 'escape'

# fish shell
stack < b              : set -l window (yabai -m query --windows --window | jq -r '.id'); \
                         yabai -m window $window --toggle float; and yabai -m window $window --toggle float; or yabai -m window east --stack $window ; \
                         skhd -k 'escape'

# Stack all windows in the currect space on top of the current window while keeping the current space layout in bsp
stack < s              : set -l window (yabai -m query --windows --window | jq -r '.id') && \
                         yabai -m query --windows --space | jq -rc --arg w $window '[.[].id] | map(select(. != $w)) | .[]' | \
                         xargs -I {} yabai -m window "$window" --stack {}; \
                         skhd -k 'escape'

####################### Resize mode ############################################

# Resize focused window towards left direction
resize < h             : yabai -m window --resize left:-20:0 || \
                         yabai -m window --resize right:-20:0

# Resize focused window towards down direction
resize < j             : yabai -m window --resize bottom:0:20 || \
                         yabai -m window --resize top:0:20

# Resize focused window towards up direction
resize < k             : yabai -m window --resize top:0:-20 || \
                         yabai -m window --resize bottom:0:-20

# Resize focused window towards right direction
resize < l             : yabai -m window --resize right:20:0 || \
                         yabai -m window --resize left:20:0

resize < left          : yabai -m window --resize left:-20:0 || \
                         yabai -m window --resize right:-20:0

# Resize focused window towards down direction
resize < down          : yabai -m window --resize bottom:0:20 || \
                         yabai -m window --resize top:0:20

# Resize focused window towards up direction
resize < up            : yabai -m window --resize top:0:-20 || \
                         yabai -m window --resize bottom:0:-20

# Resize focused window towards right direction
resize < right         : yabai -m window --resize right:20:0 || \
                         yabai -m window --resize left:20:0

# Balance all windows. Maps to `=` key
resize < 0x18          : yabai -m space --balance; skhd -k 'escape'

# Rotate tree by 90 degrees
resize < r             : yabai -m space --rotate 90

# Mirror tree y-axis
resize < y             : yabai -m space --mirror y-axis; \
                         skhd -k 'escape'

# Mirror tree x-axis
resize < x             : yabai -m space --mirror x-axis; \
                         skhd -k 'escape'

# Set all windows on active space back to normal
resize < z             : yabai -m query --windows --space | jq -re '.[] | select(."has-fullscreen-zoom" == true) | .id' | \
                         xargs -I{} yabai -m window {} --toggle zoom-fullscreen; \
                         skhd -k 'escape'

# rotate all windows clockwise
resize < c              : "$HOME/.config/skhd/yabai_script_actions.sh" rotate_clockwise

# rotate all windows counter-clockwise
resize < x              : "$HOME/.config/skhd/yabai_script_actions.sh" rotate_counter_clockwise

# Swaps the recent window with the window that's currently focused by the mouse
resize < s              : yabai -m window mouse --swap recent; \
                         skhd -k 'escape'


############################ Display mode ######################################

# Focus previous display , (Like <)
display < 0x2F         : yabai -m display --focus prev || \
                         yabai -m display --focus next; \
                         skhd -k 'escape'

# Focus next display . (Like >)
display < 0x2B         : yabai -m display --focus next || \
                         yabai -m display --focus prev; \
                         skhd -k 'escape'

# Send window to north/up display and follow focus
display < up           : yabai -m window --display north; \
                         yabai -m display --focus north; \
                         skhd -k 'escape'

# Send window to down/south display and follow focus
display < down         : yabai -m window --display south; \
                         yabai -m display --focus south; \
                         skhd -k 'escape'

# Send window to right/east display and follow focus
display < right        : yabai -m window --display east; \
                         yabai -m display --focus east; \
                         skhd -k 'escape'

# Send window to left/west display and follow focus
display < left         : yabai -m window --display west; \
                         yabai -m display --focus west; \
                         skhd -k 'escape'

# Focus display by number
display < 1           : yabai -m display --focus 1; skhd -k 'escape'
display < 2           : yabai -m display --focus 2; skhd -k 'escape'
display < 3           : yabai -m display --focus 3; skhd -k 'escape'
display < 4           : yabai -m display --focus 4; skhd -k 'escape'

##################### Window mode ##############################################

# create desktop and follow focus
# bash shell
# window < c            : yabai -m space --create; \
#                       index="$(yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index')"; \
#                       yabai -m space --focus "${index}"; \
#                       skhd -k 'escape'

# create desktop and follow focus
# fish shell 
# Note must be one line
window < c                : yabai -m space --create; set -l index (yabai -m query --spaces --display | jq 'map(select(."is-native-fullscreen" == false))[-1].index'); yabai -m space --focus $index; skhd -k 'escape'

# create desktop, send window to new desktop and follow focus
# bash shell
# window < s            : yabai -m space --create; \
#                        index="$(yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index')"; \
#                        yabai -m window --space "${index}"; \
#                        yabai -m space --focus "${index}"; \
#                        skhd -k 'escape'

# create desktop, send window to new desktop and follow focus
# fish shell 
# Note must be one line and run one time in shell before using
window < s              : yabai -m space --create; set -l index (yabai -m query --spaces --display | jq 'map(select(."is-native-fullscreen" == false))[-1].index'); yabai -m window --space $index;  yabai -m space --focus $index; skhd -k 'escape'


# destroy current desktop and follow focus to previous desktop
# bash shell
# window < x            : index="$(yabai -m query --spaces --space | jq '.index - 1')"; \
#                         yabai -m space --destroy; \
#                         yabai -m space --focus "${index}"; \
#                         skhd -k 'escape'

# fish shell
window < x            : set -l index (yabai -m query --spaces --space | jq '.index - 1'); \
                         yabai -m space --destroy; \
                         yabai -m space --focus "$index"; \
                         skhd -k 'escape'


# toggle window native fullscreen
window < f            : yabai -m window --toggle native-fullscreen; skhd -k 'escape'

# send current window to i-th space and follow focus
window < left         : yabai -m window --space prev; \
                        yabai -m space --focus prev; \
                        skhd -k 'escape'
window < right        : yabai -m window --space next; \
                        yabai -m space --focus next; \
                        skhd -k 'escape'
window < 1            : yabai -m window --space 1; \
                        yabai -m space --focus 1; \
                        skhd -k 'escape'
window < 2            : yabai -m window --space 2; \
                        yabai -m space --focus 2; \
                        skhd -k 'escape'
window < 3            : yabai -m window --space 3; \
                        yabai -m space --focus 3; \
                        skhd -k 'escape'
window < 4            : yabai -m window --space 4; \
                        yabai -m space --focus 4; \
                        skhd -k 'escape'
window < 5            : yabai -m window --space 5; \
                        yabai -m space --focus 5; \
                        skhd -k 'escape'
window < 6            : yabai -m window --space 6; \
                        yabai -m space --focus 6; \
                        skhd -k 'escape'
window < 7            : yabai -m window --space 7; \
                        yabai -m space --focus 7; \
                        skhd -k 'escape'
window < 8            : yabai -m window --space 8; \
                        yabai -m space --focus 8; \
                        skhd -k 'escape'
window < 9            : yabai -m window --space 9; \
                        yabai -m space --focus 9; \
                        skhd -k 'escape'
window < 0            : yabai -m window --space 10; \
                        yabai -m space --focus 10; \
                        skhd -k 'escape'

window < alt - 1      : yabai -m window --space 11; \
                        yabai -m space --focus 11; \
                        skhd -k 'escape'
window < alt - 2      : yabai -m window --space 12; \
                        yabai -m space --focus 12; \
                        skhd -k 'escape'
window < alt - 3      : yabai -m window --space 13; \
                        yabai -m space --focus 13; \
                        skhd -k 'escape'

# Switch layout of current desktop between bsp and stack
window < space        : yabai -m query --spaces --space | \
                        jq -re ".type" | \
                        xargs -I {} bash -c \
                        "if [ {} = 'stack' ]; \
                        then yabai -m space --layout bsp; \
                        else yabai -m space --layout stack; \
                        fi"; \
                        skhd -k 'escape'
