# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

right_format = "$time"

[time]
disabled = false
format = '[$time]($style) '
time_format = '%T'
utc_time_offset = '-5'
time_range = '-'

[shell]
fish_indicator = '󰈺 '
powershell_indicator = '_'
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = true


[git_branch]
symbol = "🌱 "


[git_commit]
style = "normal"
only_detached = true
tag_disabled = false
tag_symbol = " 🔖"
format = "\\[[$hash](bold green)[$tag](bold red)\\] "

[git_status]
style = "normal"
conflicted = "[ ](bold red)"
ahead = "[↑×${count}](bold green)"
diverged = "[↑×${ahead_count}](bold green) [↓×${behind_count}](bold red)"
behind = "↓×${count}(bold red)"
stashed = "[⊙](bold purple)"
staged = "[](bold blue)"
untracked = "[](normal)"
deleted = "[](bold red)"
modified = "[](#FF7F00)"

[python]
symbol = '👾 '


[conda]
symbol = " "
