# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

right_format = "$time"

[time]
disabled = false
format = '[$time]($style) '
time_format = '%T'
utc_time_offset = '-5'
time_range = '-'

[shell]
fish_indicator = '󰈺 '
powershell_indicator = '_'
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = true


[git_branch]
symbol = "🌱 "

[python]
symbol = '👾 '


[conda]
symbol = " "
